# Optional local upgrade: BASE_IMAGE must be an existing same-project runtime.
# The normal Dockerfile remains the clean-machine build entrypoint.
ARG BASE_IMAGE=ppt-generator-api:pre-langfuse
FROM ${BASE_IMAGE} AS runtime
USER root
WORKDIR /srv
ARG PIP_INDEX_URL=https://pypi.org/simple
COPY requirements.txt .
RUN pip install --no-cache-dir -i ${PIP_INDEX_URL} -r requirements.txt
COPY app ./app
ARG RUNTIME_USER=root
USER ${RUNTIME_USER}
